{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "counter-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "counter-service.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "counter-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "counter-service.fullname" . }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "counter-service.fullname" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "counter-service.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
